### ISSUE TITLE
Number cannot be shown

### ISSUE THREAD

**Issue by WordlessEcho** [wongchito/RailMapGenerator#1]
In Guangzhou Metro style, number will not display in interchange tag. It will also affect the font of texts that before number. 

For example, here I input the "东莞2号线" and "东莞1号线". But 1 and 2 does not been displayed and font size of "东莞" change to 17px.
![IMG_20191218_013624](https://user-images.githubusercontent.com/12007025/71020422-3e474f00-2137-11ea-9667-e84ffecd55e1.jpg)

```HTML
<g text-anchor="middle" transform="translate(174.75932826693708,143)">
  <use xlink:href="#intbox_gz" fill="#ED1C24" y="0"></use>
  <text y="8.5" class="rmg-name__zh rmg-name__gzmtr--int rmg-name__gzmtr--white-fg rmg-name__gzmtr">
    <tspan font-size="17px" alignment-baseline="central">东莞</tspan>
    <tspan dy="-1" alignment-baseline="central">号线</tspan>
  </text>
  <text y="19.5" class="rmg-name__en rmg-name__gzmtr--int rmg-name__gzmtr--white-fg rmg-name__gzmtr">Dongguan Line 2</text>
</g>
```

**Comment by wongchito** [comment]
Hi. I had been aware of this issue. This is due to a naive method for splitting digits and Han characters to agree with the official Guangzhou Metro style. For example, "1号线" should be the combination of a larger "1"  and smaller "号线". 

I am currently investigating a better method to solve this issue, such that all kinds of combinations of digits and Han characters could be correctly split and styled.

**Comment by wongchito** [comment]
@WordlessEcho Hi. The most recent push [f1c2153](https://github.com/wongchito/RailMapGenerator/commit/f1c2153360de76729fd809ca4199aeb26e868fca) fixed the issue of improperly splitting and styling line names in Guangzhou Metro style. 

However, I am still investigating the solution to scale oversized line names.
