### ISSUE TITLE
Panel style for gzmtr.

### ISSUE THREAD

**Issue by xiaobaimao233** [wongchito/RailMapGenerator#159]
The last few days, the Official of Guangzhoumtr made a new system map for add new line of gzmtr, and the West Extend Shunde section of Line 7 use a new Sort Station Number way like ( 7 | 01-6 ), but when I type 10-6 in the station number in the RMG, the string will go beyond the boundary(like this: https://z3.ax1x.com/2021/10/30/5zyioF.png). Could you add a function to solve this problem?

**Comment by wongchito** [comment]
Hi Xiaobaimao233,

Thanks for raising this issue. We'll try to apply the same settings for extra long station number as we did on extra long line number. Thanks!

**Comment by wongchito** [comment]
This issue is partly fix - with the corrected scaling for extra long station number. 

![rmg 2021-11-07T12_45_26 865Z](https://user-images.githubusercontent.com/9390786/140645462-48f12f8a-a541-4624-8dae-5264c2f0ebad.png)

Next step will be correcting the style for line name box for Foshan Line 2.

**Comment by xiaobaimao233** [comment]
Thanks to solve this problem!

**Comment by wongchito** [comment]
Hi! The line name box (line icon) has been fixed in the latest online version (3.10.2). The error in the template of Guangzhou Metro Line 7 has also been fixed in the same release.

![rmg 2021-11-08T17_46_21 171Z](https://user-images.githubusercontent.com/9390786/140792623-97fc8db3-8172-4d6c-8793-d26d5e141fa5.png)
