### ISSUE TITLE
SVG incompatibility

### ISSUE THREAD

**Issue by Rongronggg9** [wongchito/RailMapGenerator#2]
Exported SVG can be displayed perfectly in Chrome but Adobe Illustrator 2020 (also Photoshop) will processes almost everything wrongly.

Besides, even other browsers cannot display it properly.

It seems that an exported SVG (or modified one) will be finally converted to PNG (in my case, it must be opened in Cent Browser, a Chromium fork, using built-in web-page screenshot, to get a proper PNG), to make it usable.

That means, exported SVG is limitedly editable and usable.

The new feature "Download PNG" solves some aspects of these problems.

But:
1. Size is fixed.
2. More limited when edit.
3. Unreasonable transparent area.

**Comment by wongchito** [comment]
Hi. Thanks for getting in touch. 

I have been notified several times because of the issue when opening exported SVG in Adobe Illustrator. From some of the screenshots I noticed that the unstyled elements are exactly the those who are styled by CSS class and are displayed properly in Chrome. I guess Adobe Illustrator fails to read (or isn’t supported to read) CSS stylesheet. (I personally didn’t install Illustrator and I can’t verify this.)

The use of CSS is to reduce the duplicated attributes (especially `font-family`) set to the large amounts of `text` nodes in the canvas and needed to be styled with font etc. To reduce

**Comment by wongchito** [comment]
Sorry for closing this issue by mistake. 

The “Download as PNG” feature is deemed to ease the difficulty of screen capturing the canvas, so I didn’t consider the needs of modifying it. (To modify the canvas, please refer to front-end manipulation currently. )

The size of the exported PNG is two times larger than that is shown in the webpage, while the aspect ratio remains unchanged. It should be clear enough to show the smallest text. 

The background will be added in next update, but could you tell me if a transparent background would cause any problem.

**Comment by PassionPenguin** [comment]
Maybe a transparent background is better?
or maybe @author can provide a panel to choose the background color...?

**Comment by Rongronggg9** [comment]
@PassionPenguin 
> Maybe a transparent background is better?

@wongchito 
> but could you tell me if a transparent background would cause any problem.

When we need to modify the image, a transparent background is better, absolutely, but how if we use it instantly (without any additional edit)?
In some case, especially some instant messengers, **the background will be filled with black**. If somebody uses this generator on mobile phone, that will be inconvenient to edit the image to avoid the problem. As for those who need to modify the image for some reason or other, the white background should not be difficult to remove. (but what can they do with a PNG...? )


@PassionPenguin 
> or maybe @author can provide a panel to choose the background color...?

You might mention a wrong person...?
BTW, if *Force Dark Mode for Web Contents* (chrome://flags/#enable-force-dark) enabled, now it will perform strangely, but in previous transparent background version it can perform almost properly. It may be a advantage of transparent background...? **Though that's not a bug at all, lol.**

@wongchito 
> The size of the exported PNG is two times larger than that is shown in the webpage, while the aspect ratio remains unchanged. **It should be clear enough to show the smallest text.**

Although it's clear enough to show the smallest text, but when resizing... 
(in the case below, Photoshop, resampling: Bicubic Sharper, though **all resampling methods process terribly**)
![origin](https://user-images.githubusercontent.com/15956627/74900355-73437c80-53da-11ea-821e-83ff020e88c4.png)
origin

![.5x)](https://user-images.githubusercontent.com/15956627/74898912-42614880-53d6-11ea-86cd-90afd8487d26.png)
.5x

![.25x)](https://user-images.githubusercontent.com/15956627/74898988-89e7d480-53d6-11ea-9a1a-065d905946af.png)
.25x

Since there is text, **resizing may cause serious sharpness reduction. Would it be possible to customize the size of an exported PNG?**

(A typical example: one side of a **Telegram sticker** should be 512px and the other should be 512px or less. )

**Comment by wongchito** [comment]
> As for those who need to modify the image for some reason or other, the white background should not be difficult to remove. (but what can they do with a PNG...? )

For [example](http://www.ditiezu.com/thread-644863-1-1.html), one could use Photoshop to apply the generated railway map with transparent background onto a photo with real platform screen door. This was the reason why I used transparent background previously. 

> As for those who need to modify the image for some reason or other, the white background should not be difficult to remove. (but what can they do with a PNG...? )

Yes, you are right. Including removing background and configuring light effect etc, it's not a difficult for PS users. This is the reason why I use white background now. 

> BTW, if Force Dark Mode for Web Contents (chrome://flags/#enable-force-dark) enabled, now it will perform strangely, but in previous transparent background version it can perform almost properly.

I did try the force dark mode and I also found this issue. Thus I have already started writing CSS style sheet for dark mode. But this is indeed not an urgent task so it would not be released soon. 

> Would it be possible to customize the size of an exported PNG?

This is a really good suggestion and I will consider improving the 'Export' dialogue.

**Comment by wongchito** [comment]
@Rongronggg9 Background transparency, border and scaling of the exported PNG/SVG can now be customised. ([b793789](https://github.com/wongchito/RailMapGenerator/commit/b7937892fc50d1597cd155173675753b5fa95b1e))

**Comment by Rongronggg9** [comment]
@wongchito That's awesome.
But in my case, I need to export a PNG in 512px precisely. You don't really need to add this feature because that's a really rare need. I can calculate and change the option value to do that.

**Comment by wongchito** [comment]
@Rongronggg9 Just a wee reminder. The size of the exported PNG is calculated by **original size** times **device pixel ratio** (you normally customise this in system's settings) times **scale** (chose from the selector). 

The incompatibility of SVG may not be fixed because
1. it can be opened in browser properly;
2. I've tried as much as I can to maintain the style when it's opened in Adobe Illustrator, but
3. Illustrator does not support font fallback list so it's not possible to solve this issue but remain the same appearance of the image at the same time.

If there isn't any further question regarding to this issue, I'd kindly ask to the close this issue.

**Comment by Rongronggg9** [comment]
@wongchito 
> The size of the exported PNG is calculated by original size times device pixel ratio (you normally customise this in system's settings) times scale (chosen from the selector).
I know that. But I still insist that exporting a PNG with target size should be better. Maybe it's my stubbornness, anyway.

Thanks for your effort.
I am just a perfectionism and put forward some of my own suggestions based on it (and said a lot of nonsense). I do apologize if any displeasure caused.

_BTW, now the template of GF Line is still using the info panel type of Phase 2, I guess you might forget to change it back.
(that issue is locked so I put it here.)_

**Comment by wongchito** [comment]
@Rongronggg9 I definitely know and agree that fully customising target size/scale of the PNG would be better, but I should also care about the ease of use for average users. 

The best solution would be a drop down list for selecting pre-set scales combined with an input box for editing manually. However this could not be implemented at the moment because the library I used (Material-UI) doesn't support this feature in its core module. 

I appreciate every suggestion made to this project leading to a better generator. Please do open new issues if you find something needs to be fixed or if you have any suggestions.

**Comment by PassionPenguin** [comment]
(the exported images' sizes are large.. due to base64/Data url

-- MaterialUI has some shortages, right now...
