### ISSUE TITLE
Change The Name of "South Huangpi Road" to "Site of the First CPC National Congress · South Huangpi Road" in Shanghai Metro Line 1 Template

### ISSUE THREAD

**Issue by XHG78999** [wongchito/RailMapGenerator#201]
I see The "South Huangpi Road" changed its name at 2021.6.20 to "Site of the First CPC National Congress · South Huangpi Road Station" to celebrate the CPC 100 years.
The name is using in the really world now.(See image)

Actually,i see the station name of Line 10 (Xintiandi), Line 13 (Xintiandi) is changed right now.

_PS:In Shanghai Metro Line 1 Template, The "Jinjiang Park" is "JinJiang Park", and missing the railway service of Shanghai South Railway Station.I think it's wrong too. Because of I find many translation bugs in templates, I think I can validate the translations for this._

**Comment by XHG78999** [comment]
Offical Indoor Map
![image](https://user-images.githubusercontent.com/53939187/145565986-7069190a-b3c0-4eb6-a6a1-cbb37bc5bcdc.png)

**Comment by thekingofcity** [comment]
Hi, though great efforts are put to make the templates, there are definitely some mistakes and I apologize for those inconveniences.

As you observed, the template of 1 is not updated because it is an old one which added before the change.

You are always welcome to make your contribution to the templates as well as the whole project. Open pull requests for these translation fixes will be appreciated. *[See this link if you wish to make changes.](https://github.com/wongchito/RailMapGenerator/issues/199#issuecomment-988835446)*

> I'm curious about the indoor maps in baike, where do they come from?

**Comment by thekingofcity** [comment]
Updated in 9692dc3 and released in 3.10.22
