### ISSUE TITLE
Errors In Shanghai Metro Line 2 Template

### ISSUE THREAD

**Issue by XHG78999** [wongchito/RailMapGenerator#203]
## Translate Error
Correct | Wrong
Zhangjiang High Technology Park | Zhangjiang High-Technology Park
Tang Town | Tangzhen
Haitian No.3 Road | Haitiansan Road
## Station Error
Missing Jing'an Temple Station
_PS:I think we need to have an own small-version update to fix more translate errors,etc._

**Comment by XHG78999** [comment]
Offical Art Map
![242dd42a2834349b033ba77ff6a502ce36d3d43910b3](https://user-images.githubusercontent.com/53939187/145569024-29db8530-dbc0-463f-a795-bc9a1978826e.jpg)

**Comment by thekingofcity** [comment]
Hi, like what I suggested in #201, it would be great for you to fix these texts in the online editor and open the pull request.

Or if you are unable to do this due to time or other constraints, you may follow the [wiki on how to contribute line templates section](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates) and upload the fixed template.

Or, let me fix this problem but it may take some time.

**Comment by thekingofcity** [comment]
Hi, as I go over the baike again, I find some conflicts in the translation, like the *Tangzhen* and *Haitiansan Road*. Maybe I need to go to the field or could you provide some real-world photos?

**Comment by XHG78999** [comment]
In #11 , you (@thekingofcity) send a indoor map that the Tangzhen, Haitiansan Road is the correct. In the map on Shanghai Metro Offical Site, The Tangzhen and Haitiansan Road is correct too. But in this map, Zhangjiang High-Technology Park is wrong.
_PS:The Jing'an Temple missing the transfer infomation of Line 7, so the commit 5ddddacb isn't do anything useful._

**Comment by thekingofcity** [comment]
Hi, the transfer info of Line 7 at *Jing'an Temple* is fixed, and *Zhangjiang High-Technology Park* is renamed to *Zhangjiang High Technology Park*.
