### ISSUE TITLE
Rewrite Add Station Action

### ISSUE THREAD

**Issue by wongchito** [wongchito/RailMapGenerator#239]
Currently adding a station in RMG requires 4 or 5 inputs to form a natural language query:
1. A preposition (before or after)
2. A pivot station
3. A target location (main line, upper branch, lower branch, new upper branch, new lower branch)
4. A station where the newly created branch ends (only applicable if new branch is selected in 3)

Though the action query is in natural language, it requires additional conversion from the actual user needs. It's reported that users are confused by the description of 3, when they're trying to add a new branch (a station on a new branch) to an existing complicated line. 

Also, when we come to V5, we allow users to create another line which shares track with the existing one in a same canvas (e.g. Shanghai Metro Line 3 & 4). The current query won't fit for the new features. 

Therefore, I propose a new add station action for RMGV5, which takes x inputs as described below: 

1. On which line - main line, existing branch 1, existing branch 2, ..., new branch _(selections can be populated by `helper.branches` state)_
2. Between which stations
  2.1. For main line and existing branch, two adjacent stations need to be selected. 
  2.2. For new branch, a branching out station and the station where the branch ends need to be selected.

For track sharing stations, (to be added)

**Comment by thekingofcity** [comment]
A target location and where the branch ends require users to be familiar with the internal data structure. I'm in favor of the new action which adds stations after selecting branches.

For track sharing, since it is a pure svg metadata that has nothing to do with `stn_list` and branches, it will use its UI diag and actions on its data. The new add station part will help it to have something for reference.
