### ISSUE TITLE
关于线路图的一些建议

### ISSUE THREAD

**Issue by 3394946742** [wongchito/RailMapGenerator#31]
您好！
我是一个轨道交通爱好者，经常使用这个网站制作线路图。
下面是我的一些建议，望采纳：
1.线路图的风格只有香港、广州、上海，能不能考虑加入其它的风格？（如北京、西安、成都、重庆等）
2.新建的一张画布（空白版），如果设为广州地铁风格，车站总是以TW 00标注，TW是不能改的，以后能否更改TW？
3.颜色选择方面，虽然有西安的线路栏，但是打开之后什么都没有，是否可以增加西安地铁的线路颜色？
4.会不会考虑环线？
5.会不会考虑一些站台导向或者地铁内部的LED/LCD线路图？
6.因为很多地铁线路开通时总会有几个站因为种种原因而不同步开通，能否考虑增加暂缓开通的标识？
7.能否跟香港/广州的风格一样，上海风格也能加一些图标（如机场/游乐园/火车站/公园等）？
8.线路图中，能否可以更加自定义化些？（如上海地铁，可以增加多种语言；自己考虑换乘站加不加黑线或者增加自定义图标）？
9.因为线路规划可能换乘站会有所变更，而我已经又新建了一个画布，旧存档就没有了。只能用画图/PPT等软件做补丁，能否考虑保存上一个编辑的存档或更多？
谢谢！（qq：3394946742【邮箱+@qq.com】）

**Comment by thekingofcity** [comment]
以下是与上海风有关建议的回复:

> 7.能否跟香港/广州的风格一样，上海风格也能加一些图标（如机场/游乐园/火车站/公园等）？

在考虑之中, 实现日期待定. 
目前上海地铁只有火车站和磁悬浮有特殊样式, 计划中可能还会增加个迪士尼乐园.

> 8.线路图中，能否可以更加自定义化些？（如上海地铁，可以增加多种语言；自己考虑换乘站加不加黑线或者增加自定义图标）？

* 多种语言暂时不会考虑, 目前没有看到官方的实现并且也不是很能理解具体效果
* 换乘站加不加黑线应该不可自定义, 如上所述, 这是官方的实现
* 增加自定义图标需要本体的支持

PS: 如果有额外需求可以每个需求单开issue, 我们会单独评估, 也方便后人查询

**Comment by wongchito** [comment]
> 1.线路图的风格只有香港、广州、上海，能不能考虑加入其它的风格？（如北京、西安、成都、重庆等）

As an individual, I'm not able to maintain too many styles or features. Also, I'm not familiar with the transport systems in the cities other than where I live. So it maybe possible for me to add a style in the future if it has detailed design standards provided. From a more practical view, it would be better for you or others to contribute to this project. (We understand the relevant documentations are far from satisfying but we'll update it and provide as many help as we can.)

作為個人開發者無法同時兼顧過多風格或功能，同時亦不熟悉居住地以外的交通系統。因此我有可能在未來新增有完整設計標準的風格。但從實踐角度，由閣下或其他有志之士向該項目作出貢獻將會更好。（我們知道相關開發檔案未盡人意，但我們會持續更新它，亦會提供足夠的協助。）

> 2.新建的一张画布（空白版），如果设为广州地铁风格，车站总是以TW 00标注，TW是不能改的，以后能否更改TW？

Please edit the line number at "Design" -> "Line number". 

請於「設計」->「路線編碼」中編輯。

> 3.颜色选择方面，虽然有西安的线路栏，但是打开之后什么都没有，是否可以增加西安地铁的线路颜色？

Will be fixed in 3d45654 . 

> 4.会不会考虑环线？

Please refer to #24 .

> 5.会不会考虑一些站台导向或者地铁内部的LED/LCD线路图？

In the next big update we'll release feature of dynamic route map (DRM). Currently we're preparing for this feature. Please also refer to #11 . 

在下一個大型更新中我們將會提供動態路線圖。現時我們正在為其做準備。

> 6.因为很多地铁线路开通时总会有几个站因为种种原因而不同步开通，能否考虑增加暂缓开通的标识？

- MTR: There's no such kind of notes or symbols.  沒有該類標註或標誌。
- Guangzhou Metro: You may use "Design" -> "Notes" to add notes or add a secondary name to the station. Both methods are used by Guangzhou Metro Company. 閣下可以使用「設計」->「備註」或新增車站第二名稱。兩種方法均為廣州地鐵公司使用。

> 9.因为线路规划可能换乘站会有所变更，而我已经又新建了一个画布，旧存档就没有了。只能用画图/PPT等软件做补丁，能否考虑保存上一个编辑的存档或更多？

Please save your work in JSON format in "File" -> "Save as JSON". You can import your previous work in "File" -> "Open from JSON". We're also considering adding file management system but it'll not be available recently since it's not essential. 

請使用「檔案」->「儲存為JSON檔案」以儲存閣下的作品。閣下可以透過「檔案」->「開啟自JSON檔案」載入以前的作品。我們正在考慮新增檔案管理系統，但近期不會提供，因為其不是必要。

**Comment by maliaoshui** [comment]
6.因为很多地铁线路开通时总会有几个站因为种种原因而不同步开通，能否考虑增加暂缓开通的标识？
•MTR:通过反斜杠换行符标注暂缓开通实现
![Screenshot_20200421_154726_com android chrome](https://user-images.githubusercontent.com/63832863/79839764-9644d980-83e7-11ea-8d36-0bc00b069fbe.jpg)

**Comment by maliaoshui** [comment]
暂缓开通的终点站，可通过自定义终点站指示牌实现

**Comment by rainydew** [comment]
> 暂缓开通的终点站，可通过自定义终点站指示牌实现

v5的上海风格线路图中，暂时无法自定义终点站指示牌
后面可以考虑？

**Comment by thekingofcity** [comment]
> >  暂缓开通的终点站，可通过自定义终点站指示牌实现
>
> v5的上海风格线路图中，暂时无法自定义终点站指示牌
后面可以考虑？

上海风格暂无此种情况，就算支持也无法得知具体实现方式。
