### ISSUE TITLE
Interchange box overlaps station's English name in Shanghai Style 上海风格换乘线路和英文站名重叠

### ISSUE THREAD

**Issue by 3394946742** [wongchito/RailMapGenerator#33]
0.0 我用上海地铁的风格下载一张线路图，换乘的线路总和英文站名重叠，这是为啥

**Comment by peejayliu0517** [comment]
应该是你那个英文站名太长了，调一下尺寸可能会好些。------------------ 原始邮件 ------------------
发件人: "3394946742"<notifications@github.com>
发送时间: 2020年4月6日(星期一) 下午2:39
收件人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wongchito/RailMapGenerator] 关于下载的问题 (#33)




 
0.0 我用上海地铁的风格下载一张线路图，换乘的线路总和英文站名重&#x53E0;，这是为啥
 
&mdash;

**Comment by wongchito** [comment]
We have noticed this issue and have tried to fix this issue (but apparently it didn't work). We are still investigating how this issue is triggered and trying to find out a solution.

**Comment by 3394946742** [comment]
但是我调了尺寸依旧不行啊（也有可能是挑错了）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peejayliu0517"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 下午2:40
收件人:&nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;"Dream丶David"<3394946742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 关于下载的问题 (#33)





 应该是你那个英文站名太长了，调一下尺寸可能会好些。------------------ 原始邮件 ------------------ 
 发件人: "3394946742"<notifications@github.com&gt; 
 发送时间: 2020年4月6日(星期一) 下午2:39 
 收件人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [wongchito/RailMapGenerator] 关于下载的问题 (#33) 
 
 
 
 
   
 0.0 我用上海地铁的风格下载一张线路图，换乘的线路总和英文站名重&amp;#x53E0;，这是为啥 
   
 &amp;mdash;

**Comment by peejayliu0517** [comment]
有多大调多大（滑稽）你一百一百的上去------------------ 原始邮件 ------------------
发件人: "3394946742"<notifications@github.com>
发送时间: 2020年4月6日(星期一) 下午2:45
收件人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com>;
抄送: "peejayliu0517"<3378168659@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wongchito/RailMapGenerator] Interchange box overlaps station's English name in Shanghai Style 上海风格换乘线路和英文站名重叠 (#33)




 但是我调了尺寸依旧不行啊（也有可能是挑错了） 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"peejayliu0517"<notifications@github.com&gt;; 
 发送时间:&nbsp;2020年4月6日(星期一) 下午2:40 
 收&#x4EF6;人:&nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;; 
 抄送:&nbsp;"Dream丶David"<3394946742@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题:&nbsp;Re: [wongchito/RailMapGenerator] 关于下载的问题 (#33) 
 
 
 
 
 
  应该是你那个英文站名太长了，调一下尺寸可能会好些。------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "3394946742"<notifications@github.com&gt;  
  发送时间: 2020年4月6日(星期一) 下午2:39  
  收&#x4EF6;人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&gt;;  
  主题: [wongchito/RailMapGenerator] 关于下载的问题 (#33)  
   
   
   
   
     
  0.0 我用上海地铁的风格下载一张线路图，换乘的线路总和英文站名重&amp;#x53E0;，这是为啥  
     
  &amp;mdash;  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by 3394946742** [comment]
调高度还是长度




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peejayliu0517"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 下午2:55
收件人:&nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;"Dream丶David"<3394946742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] Interchange box overlaps station's English name in Shanghai Style 上海风格换乘线路和英文站名重叠 (#33)





 有多大调多大（滑稽）你一百一百的上去------------------ 原始邮件 ------------------ 
 发件人: "3394946742"<notifications@github.com&gt; 
 发送时间: 2020年4月6日(星期一) 下午2:45 
 收件人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;; 
 抄送: "peejayliu0517"<3378168659@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [wongchito/RailMapGenerator] Interchange box overlaps station's English name in Shanghai Style 上海风格换乘线路和英文站名重叠 (#33) 
 
 
 
 
  但是我调了尺寸依旧不行啊（也有可能是挑错了）  
   
   
   
   
  ------------------&amp;nbsp;原始邮&amp;#x4EF6;&amp;nbsp;------------------  
  发&amp;#x4EF6;人:&amp;nbsp;"peejayliu0517"<notifications@github.com&amp;gt;;  
  发送时间:&amp;nbsp;2020年4月6日(星期一) 下午2:40  
  收&amp;#x4EF6;人:&amp;nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&amp;gt;;  
  抄送:&amp;nbsp;"Dream丶David"<3394946742@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;  
  主题:&amp;nbsp;Re: [wongchito/RailMapGenerator] 关于下载的问题 (#33)  
   
   
   
   
   
   应该是你那个英文站名太长了，调一下尺寸可能会好些。------------------ 原始邮&amp;#x4EF6; ------------------   
   发&amp;#x4EF6;人: "3394946742"<notifications@github.com&amp;gt;   
   发送时间: 2020年4月6日(星期一) 下午2:39   
   收&amp;#x4EF6;人: "wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&amp;gt;;   
   抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;   
   主题: [wongchito/RailMapGenerator] 关于下载的问题 (#33)   
     
     
     
     
       
   0.0 我用上海地铁的风格下载一张线路图，换乘的线路总和英文站名重&amp;amp;#x53E0;，这是为啥   
       
   &amp;amp;mdash;   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 &amp;mdash;
