### ISSUE TITLE
How to prepare a local development environment and add more styles

### ISSUE THREAD

**Issue by thekingofcity** [wongchito/RailMapGenerator#4]
I'm really interested in this project and want to make some contribution such as adding more styles other than mtr and gzmtr. However, after some skimming on the project, I lost myself and didn't know where to start. And I was also not sure what development environment should I have (CoffeeScript required?).

Hoping to get more help from the developer :)

**Comment by wongchito** [comment]
The core modules of this project consist of 2 parts - drawing SVG and providing control panels for manipulating the line and stations. 

**Drawing SVG**

`/src/Stations.ts` - Classes for calculating all properties of station icon including name, interchange, position etc., in different styles. The base-class is `RMGStation` (default for MTR style) and all other classes inherit from `RMGStation` (e.g. `Int2Station`, `RMGStationGZ`, etc.). 

`/src/Line.ts` - Classes for drawing line and stations (with properties calculated from `Station.ts`) in different styles. The base-class is `Line` which is default for MTR and `LineGZ` is for Guangzhou Metro. 

`index.html` - Styles and elements that are used repeatedly are defined in `<style>` and `<def>`. 

**Control panels**

`/src/page_loader.ts` - Functions for initialising the panels (one for each tab). The current 2 styles share almost the same fields of parameters (some parameters are different in 'Design' tab). 

**Environments**

Only one thing is needed to be install - TypeScript. I use the other modules directly from CDN. (I didn't find a way to import Material Components (MDC) into TypeScript so `/src/page_loader.ts` is full of error messages. )

**How to start a new style (example)**

1. Create new classes `LineSZ` and `RMGStationSZ` inheriting from `Line` and `RMGStation` respectively (or `LineGZ` and `RMGStationGZ` if you prefer). 
2. Edit methods, for example, changing `RMGStationSZ.iconHTML` to accommodate the style of station icon in MTR (Shenzhen) style, or changing `LineSZ.drawLine` to use the CSS style pre-defined. 
3. Adding style-specific parameters would be much more difficult because the functions in `/src/page_loader.ts` are highly integrated. It would be made clearer in near future. 

**Other notes**

I didn't expect that somebody may wish to help adding more style one day so I didn't prepare a proper `README` and make the code to be easily followed up. This comment will be a template for me to write `README` and I will split up some of the codes such that new styles can be easily added.

**Comment by thekingofcity** [comment]
What a great tutorial and I believe adding this to the ```README``` would definitely help others.

So from the 

> I will split up some of the codes such that new styles can be easily added

It seems waiting for another few days will make it easy to read and work on?

**Comment by wongchito** [comment]
I will start the splitting-up work tonight and I will comment this issue again when new styles are possible to be added.

**Comment by thekingofcity** [comment]
Impossible speed, can't wait to see them

**Comment by wongchito** [comment]
I have now split the files for drawing SVG - `Line.ts` and `Station.ts` now become directories respectively. To start a new style, you have to

1. Add `case` for your style at `index.html:33`
2. Create new `.ts` file in `/src/Line/` and the new class must be inherit from `RMGLine`
3. Create new `.ts` file in `/src/Station` if you need a new style of station icon
4. Import your new class in `/src/Line/init.ts` header and add `case` at line 18
5. Test your code by querying `?style=[yournewstyle]` or add selection at `index.html:685`

Feel free to ask for more detail.

**Comment by thekingofcity** [comment]
After

```
> npm install -g typescript
+ typescript@3.7.5

> npm install @types/jquery
+ @types/jquery@3.3.31

> tsc
```

I still saw 127 errors and all of some were ```TS2339: Property 'xxx' does not exist on type 'HTMLElement'.``` and after some search I knew this was related to the jQuery.

But there was no problem to use the website through a local server.

Is this fine or am I missing something like error ignore settings?

---

Last few lines from the output:

> src/page_loader.ts:942:30 - error TS2339: Property 'MDCDialog' does not exist on type 'HTMLElement'.
> 942     $('#stn_delete_diag')[0].MDCDialog.listen('MDCDialog:opening', event => {
                                 ~~~~~~~~~
> src/page_loader.ts:946:30 - error TS2339: Property 'MDCDialog' does not exist on type 'HTMLElement'.
> 946     $('#stn_delete_diag')[0].MDCDialog.listen('MDCDialog:closed', event => {
                                 ~~~~~~~~~
> src/page_loader.ts:955:37 - error TS2339: Property 'MDCDialog' does not exist on type 'HTMLElement'.
> 955             $('#stn_delete_err')[0].MDCDialog.open();

**Comment by wongchito** [comment]
This issue occurs due to Material Component (MDC) not being imported. Every line of code using MDC methods (method has prefix MDC) will be marked as an error. I am investigating a way to properly import MDC so as to solve this issue and currently we should simply ignore it. 

Everything except MDC should work fine with TypeScript so please DO response to other kinds of errors.

**Comment by thekingofcity** [comment]
After some hours copying and pasting from StationGZ and Line GZ to get the drawing right, I finally made some progress on drawing lines and stations. But there were some problems I still could not figure out.

```typescript

export class RMGLineSH extends RMGLine {
    ...

    fillThemeColour() {
        super.fillThemeColour();

        // why log this._themeColour is undefined but has the right color in html
        // and remove this will remove the stroke of the circle
        $('path#' + station_id).attr('stroke', this._themeColour);
    }

    updateStnNameBg() {
        $('#current_bg').hide();  // fix the mysterious black rect
    }
}
```
You could find the full context at [LineSH.ts](https://github.com/thekingofcity/RailMapGenerator/blob/style/shmetro/src/Line/LineSH.ts#L21)
The mysterious black rect is something like
![mysterious black rect](https://raw.githubusercontent.com/thekingofcity/RailMapGenerator/style/shmetro/docs/mysterious_black_rect.png)

---

Besides, some intriguing details made me believe leaving some notes for others who want to add styles is worthwhile. You may have a look at [style_sh.md](https://github.com/thekingofcity/RailMapGenerator/blob/style/shmetro/docs/style_sh.md).

**Comment by wongchito** [comment]
I have tested with your branch. 

1. `console.log(this._themeColour)` prints correct HEX in console.
2. `rect#current_bg` is the black rectangle specifying the current station in MTR style. I should have added attribute `mtr-specific` to this element. By doing this, no more `$('#current_bg').hide()` is needed for other styles. This will be fixed in the next update. 

Note to 2: If you adding style-specific elements into the DOM, remember to add attribute `[style]-specific` and style `display: none;` to the elements. The first `script` block in `body` will handle the show/hide problem for you. 

Other note: The UA checking excludes Firefox because of the attribute `alignment-baseline` widely used is not supported. I'm investigating a way to avoid using this attribute. 

I am really appreciate the work you have done, including the docs and the new style, given the poorly-commented code. I will try to clean up my code and provide sufficient comments and guidance. 

Thank you once again.

**Comment by thekingofcity** [comment]
Thanks for the reply, these instruction greatly helped me.

However, the recent commits made me difficult to catch up. My local merge results in a lot of code from both branch which was of course undesired. And if I start from the new commit, it is also hard to grab all changed in my branch to v2.4. Maybe I'm not good at merging branches :(

The problems coming from implementing the new styles will be filed in new issues.

Hoping to hear your reply soon.

**Comment by wongchito** [comment]
I have replied to your Gmail address. 🙂

**Comment by thekingofcity** [comment]
Thanks, I'll check it

**Comment by tianxiu111111** [comment]
This is the route map of Shanghai Metro.
![Uploading Line 4.PNG…]()
 Line 11 is ordinary,Line 8 is in the some line，and Line 4 is Loop Line,Line 17 is Every Route Line Map.
![Line 17](https://user-images.githubusercontent.com/60967903/74332468-bc8b3f00-4dd0-11ea-9ed5-10a6be183f00.PNG)

![Line 11](https://user-images.githubusercontent.com/60967903/74331962-b2b50c00-4dcf-11ea-8c00-e1b519ce8e39.PNG)
![Line 8](https://user-images.githubusercontent.com/60967903/74331980-be083780-4dcf-11ea-8bd1-4c9572d4d0e0.PNG)

**Comment by tianxiu111111** [comment]
![Line 4](https://user-images.githubusercontent.com/60967903/74332602-12f87d80-4dd1-11ea-9717-a0dd974bd1c8.PNG)
![Line 8](https://user-images.githubusercontent.com/60967903/74332613-155ad780-4dd1-11ea-94e4-6a9a4580c32f.PNG)
![Line 11](https://user-images.githubusercontent.com/60967903/74332619-17bd3180-4dd1-11ea-90a8-02de04f4bcc5.PNG)
![Line 17](https://user-images.githubusercontent.com/60967903/74332622-1a1f8b80-4dd1-11ea-9d6b-7d37a4e38b42.PNG)
This is Line Map Of Shanghai Metro.

**Comment by tianxiu111111** [comment]
And This Is Has Branch Line.
![Branch](https://user-images.githubusercontent.com/60967903/74334389-c3b44c00-4dd4-11ea-93ab-937a33b1197b.PNG)

**Comment by thekingofcity** [comment]
Thanks @tianxiu111111, the new style of shanghai was already online. Check it out at the website and open new issues if you find anything not appropriate.

But keep in mind, it was in alpha stage and osi station has not implemented yet.

**Comment by tianxiu111111** [comment]
@thekingofcity Shanghai Metro New Line Logo In Now is in Down.Please Your See.
![now](https://user-images.githubusercontent.com/60967903/74435460-73ee8700-4e9f-11ea-9cfd-efc8a9ff34b7.PNG)

**Comment by thekingofcity** [comment]
> 
> 
> @thekingofcity Shanghai Metro New Line Logo In Now is in Down.Please Your See.
> ![now](https://user-images.githubusercontent.com/60967903/74435460-73ee8700-4e9f-11ea-9cfd-efc8a9ff34b7.PNG)

@tianxiu111111  可以描述一下哪里不对吗?

**Comment by tianxiu111111** [comment]
@thekingofcity 这个x号线的框框太窄了，希望你做宽一点，像个正方形一样。因为
如果线路号是两位数，那么长方形就会令数字跑出框内，影响美观。

**Comment by thekingofcity** [comment]
@tianxiu111111 这个其实是更大的一个问题下的细节, 我现在连两位数数字间的间距和字号都无法确认, 可以提供一些更详细的设计指导吗? 之前已经调整过希望长方形可以包括下两位数. 但目前效果不尽人意

**Comment by tianxiu111111** [comment]
不好意思这个你就问错人了，我是新人，这方面我一窍不通，你去找别人吧。不过还是很期待新版本！

**Comment by tianxiu111111** [comment]
好像问到你的难点了，那说说别的吧。上海地铁的线路图有3块吊板，一块是显示当前站名和前后站名的，另一块是显示列车前进方向的，还有一块显示线路每一站的名字和换乘线路的。为什么这里只有2块？

**Comment by thekingofcity** [comment]
@tianxiu111111 
![image](https://user-images.githubusercontent.com/3353040/74530098-39025700-4f64-11ea-96a1-d72f4c8e6582.png)

不知道这样是不是好一点了? 但我还是觉得正方形怪怪的

**Comment by thekingofcity** [comment]
@tianxiu111111 3块吊板的问题之前和项目作者进行过沟通, 目前整个项目只支持两个吊板, 等项目支持后我会再添加的

除此之外, 大站车和站外换乘也都没有实现, 虽然大站车是在这两天刚刚上线的

**Comment by tianxiu111111** [comment]
@thekingofcity 还有个问题，支线那根线是不是太细了？
![10](https://user-images.githubusercontent.com/60967903/74703155-3f841d80-5247-11ea-8ae5-95880546eef6.PNG)

**Comment by thekingofcity** [comment]
@tianxiu111111 支线在测试时没有如此迷的线路安排, 临时解决方法可以调整宽度, 之后我会让支线的宽度恒定

**Comment by thekingofcity** [comment]
@tianxiu111111 出站换乘也更新了, 欢迎体验使用

**Comment by tianxiu111111** [comment]
@thekingofcity 能不能增加环线？

**Comment by PassionPenguin** [comment]
环线早就有了

**Comment by PassionPenguin** [comment]
当然不确定申通是否有
羊角的做法很简单，支线出来，合并回去，删掉外面冗余的就行

**Comment by thekingofcity** [comment]
@tianxiu111111 @PassionPenguin 上海的环线还涉及到与4号线并行的部分, 所以目前没有实现的打算, 还要看作者的更新
PS 第3块吊板做好了, 欢迎体验

**Comment by tianxiu111111** [comment]
@thekingofcity 红线右面的线颜色应该是灰色的，请看一下
![意见](https://user-images.githubusercontent.com/60967903/75105428-15b76600-564e-11ea-970f-7c62e1ed62f6.PNG)

**Comment by thekingofcity** [comment]
@tianxiu111111 [40楼的帖子是全色的](http://shanghai.metrofans.cn/thread-254544-3-1.html), [但我现在也有翻到半灰色的](https://m.weibo.cn/status/4440344063735939), 有更加确切的资料吗?

**Comment by thekingofcity** [comment]
应该是只有起始站才是全色的，我明天修复一下

**Comment by tianxiu111111** [comment]
@thekingofcity 能不能增加门灯？

**Comment by thekingofcity** [comment]
@tianxiu111111
可否详细解释下? 不是很理解
PS 目前已完成除大站车以外的功能, 除非意外不再计划安排新功能了, 大站车也估计在后两个月内实现

**Comment by tianxiu111111** [comment]
@thekingofcity 就是红圈里面的东西
![门灯](https://user-images.githubusercontent.com/60967903/75520189-ec2c7f00-5a3f-11ea-8079-d471ceed3604.PNG)
，还有，现实中的地铁线路图是这样
![11号线](https://user-images.githubusercontent.com/60967903/75520131-c606df00-5a3f-11ea-82a7-5c1e5eacc7df.PNG)

**Comment by tianxiu111111** [comment]
@thekingofcity 忘记说了，换乘支线车站是有分支的
![支线](https://user-images.githubusercontent.com/60967903/75520649-fbf89300-5a40-11ea-98fe-2e97d2df6554.PNG)

**Comment by thekingofcity** [comment]
> 
> 
> @thekingofcity 忘记说了，换乘支线车站是有分支的
> ![支线](https://user-images.githubusercontent.com/60967903/75520649-fbf89300-5a40-11ea-98fe-2e97d2df6554.PNG)

@tianxiu111111 可否给张实景图参考? 之前支线换乘站一直没搜到图

**Comment by thekingofcity** [comment]
> 
> 
> @thekingofcity 就是红圈里面的东西
> ![门灯](https://user-images.githubusercontent.com/60967903/75520189-ec2c7f00-5a3f-11ea-8079-d471ceed3604.PNG)
> ，还有，现实中的地铁线路图是这样
> ![11号线](https://user-images.githubusercontent.com/60967903/75520131-c606df00-5a3f-11ea-82a7-5c1e5eacc7df.PNG)

@tianxiu111111 红圈目前不打算实现, 不知道mtr和广州是否有实现物理元素? @wongchito 

支线的斜分叉参考的是10号线, 虽然11号线和5号线使用的图上所示, 但我个人还是倾向于斜支线

**Comment by Rongronggg9** [comment]
@thekingofcity 
> 不知道mtr和广州是否有实现物理元素? 
MTR 似乎没有，广州是有的，站牌下方的椭圆就是门灯，作者实现了不同的门灯颜色，其实对应的是灯罩的颜色。
旁边的屏蔽门编号也可以算，毕竟那是另外贴上去的(光速逃

**Comment by wongchito** [comment]
> 作者实现了不同的门灯颜色，其实对应的是灯罩的颜色。

感謝您的回答。實際上廣州地鐵風格提供了多種幕門資訊板樣式，以變換色帶寬度、幕門燈形狀顏色及位置、幕門號顏色及位置。

**Comment by thekingofcity** [comment]
> 
> 
> > 作者实现了不同的门灯颜色，其实对应的是灯罩的颜色。
> 
> 感謝您@Rongronggg9的回答。實際上廣州地鐵風格提供了多種幕門資訊板樣式，以變換色帶寬度、幕門燈形狀顏色及位置、幕門號顏色及位置。
> 
> @thekingofcity It's save as the `panel_type` property in `RMGParam`.

@wongchito thx, I will have a look

@tianxiu111111 我可能要花一些时间来实现多种风格的样式, 不过我打算优先处理下```换乘支线车站是有分支的```, 不知可否给些图片参考

**Comment by thekingofcity** [comment]
I'm afraid this issue contains more than it should has. I have referenced problems in different issues such as #19 and #20. Please open new issues if there are new problems.

新的问题麻烦开新的issue, 这个issue过长且偏离了主题, 谢谢 @tianxiu111111

**Comment by Rongronggg9** [comment]
> 實際上廣州地鐵風格提供了多種幕門資訊板樣式，以變換色帶寬度、幕門燈形狀顏色及位置、幕門號顏色及位置。

尽管广佛线二期(新城东—澜石)的屏蔽门贴纸与其余段是相同的，但屏蔽门门灯的设计是不同的，可见于 [[1号线] [走遍中国]（佛山）告白边界—剪纸下的悸动瞬间For Line GF（上）（56P）](http://www.ditiezu.com/forum.php?mod=redirect&goto=findpost&ptid=551873&pid=8523542) 。
如您需要更清晰的照片，我可前往拍摄。

**Comment by wongchito** [comment]
@Rongronggg9 Thanks for the information. Info panel type of Guangfo Line Phase 1, along with Guangzhou Metro Line 1, Line 4 and Line 5 will be implemented recently.

**Comment by wongchito** [comment]
@Rongronggg9 Added in [71ba0fa](https://github.com/wongchito/RailMapGenerator/commit/71ba0fa2096fdaf9d2f4b4de5b5e1145624c3ee5).

**Comment by Rongronggg9** [comment]
@wongchito It should be Phase 2, not Phase 1.
[](http://www.fmetro.net/UploadFiles/Products/2019/1/201901030942500481.png)

[广佛线各区间开通时间一览表-佛山地铁](http://www.fmetro.net/Item/1688.aspx)

**Comment by Rongronggg9** [comment]
BTW I am working on a simple project that directly modify/generate the .json of RMG in order to deal with complex lines conveniently. It may use some of your templates, especially color templates. I wonder if there are any limitations when I use them.

**Comment by wongchito** [comment]
@Rongronggg9 I'll fix the error of the description in the coming commit.
